name: getTrojan

# 触发条件
on:
  workflow_dispatch:

  schedule:
    - cron: '*/45 * * * *'

env: # 设置环境变量
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 加载缓存
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: 执行任务
      env:
        trojan_url: ${{secrets.trojan_url}}
        bot_token: ${{secrets.bot_token}}
        chat_id: ${{secrets.chat_id}}
      run: |
        python ./utils/getlinks.py
    - name: Commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add links
        if ! git diff --cached --quiet; then
          git commit -m "Trojan节点更新时间 $(date '+%Y-%m-%d %H:%M:%S')"
          git pull --ff-only origin master
          git push origin master
        else
          echo "No changes to commit"
        fi

