name: get_vmess

# 触发条件
on:
  workflow_dispatch:

  schedule:
    - cron: '30 */4 * * *'

env: # 设置环境变量
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 加载缓存
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements2.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements2.txt
    - name: 执行任务
      env:
        vemss_key: ${{secrets.vemss_key}}
        vmess_api: ${{secrets.vmess_api}}
        vmess_api2: ${{secrets.vmess_api2}}
        vemss_id: ${{secrets.vemss_id}}
        vmess_code: ${{secrets.vmess_code}}
        recomm_code: ${{secrets.recomm_code}}
        vmess_token: ${{secrets.vmess_token}}
        vmess_name: ${{secrets.vmess_name}}
        bot_token: ${{secrets.bot_token}}
        chat_id: ${{secrets.chat_id}}
      run: |
        python ./utils/get_vmess.py
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ./links
        git commit -m "vmess节点更新时间 $(date '+%Y-%m-%d %H:%M:%S')"
        git config pull.rebase false
        git pull origin master
        git push origin master

